name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Frontend and Build
        run: |
          npm install
          npm run build

      - name: Deploy to VPS
        uses: appleboy/scp-action@master
        with:
          host: 152.53.111.11
          username: root
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          source: "dist/*,backend/*,package.json,package-lock.json"
          target: "/var/www/html/landingPage/"
